version: '3'

services:
  angular-app:
    image: alexandergerus/angular-graphql-apollo
    container_name: container-ui
    restart: unless-stopped
    networks:
      - caddy
  caddy:
    image: caddy:2
    container_name: caddy
    restart: always
    ports:
      - 80:80  # Needed for the ACME HTTP-01 challenge.
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy-config:/config
      - ./caddy-data:/data

networks:
  caddy:
    external: true

volumes:
  caddy_data:
    external: true
  caddy_config:
    external: true
